/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it0003_HelloWorldJNI */

#ifndef _Included_it0003_HelloWorldJNI
#define _Included_it0003_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it0003_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it0003_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
